version: "3"
services:
  vouch-client:
    image: vouch-client
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  vouch-be:
    image: vouch-be
    ports:
      - "3001:3001"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local